# Generated by Django 2.2 on 2019-05-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicwand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='survachki',
            name='category',
        ),
    ]
