# Generated by Django 2.2 on 2019-05-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20190518_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchers',
            name='category',
        ),
    ]
