# Generated by Django 2.2 on 2019-05-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20190523_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetchers',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='magicwand',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='survachki',
            old_name='user',
            new_name='username',
        ),
    ]
